# nothing here
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_ADC=y

CONFIG_ADC_ADS1263=y

CONFIG_LOG=y
CONFIG_ADC_LOG_LEVEL_DBG=y
# Enable floating point format support for printk and logging
CONFIG_CBPRINTF_FP_SUPPORT=y

# Ensure the Hardware Floating Point Unit is active (if your MCU has one)
CONFIG_FPU=y
CONFIG_LOG_BUFFER_SIZE=32768
CONFIG_LOG_MODE_IMMEDIATE=y